FROM ubuntu:18.04

EXPOSE 1337

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y install socat coreutils && \
    apt-get -y install python3 

RUN apt-get -y install gdb git python3-pip python3-dev libssl-dev libffi-dev build-essential nano tmux ruby && \
    git clone https://github.com/pwndbg/pwndbg && \
    cd pwndbg && \
    ./setup.sh && \
    cd .. && \
    python3 -m pip install -U pip && \
    python3 -m pip install -U pwntools && \
    python3 -m pip install -U ROPgadget && \
    gem install one_gadget

COPY chall/flag.txt /
COPY chall/app /
COPY chall/app.c /
COPY handle_conn.py /
COPY sol.py /

RUN gcc -fstack-protector -o app app.c && \
    chmod 555 /app && \
    chmod 444 /flag.txt

CMD socat -T 30 \
    TCP-LISTEN:1337,nodelay,reuseaddr,fork \
    EXEC:"python3 handle_conn.py"
