version: '3'

services:
  main_app:
    build: .
    environment:
      SQLTUT_PORT: 80
      SQLTUT_HOST: "0.0.0.0"
      SQLTUT_DBURI: "mysql://branko:22b319a4880b353aa9659be58660241f9@database/database"
      # NE DALJSA OD 10!!
      SQLTUT_HASHING_SECRET: v3s01jc7
    ports:
      - 80:80

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "c76b525e53f3b9204222b319a4880b353aa9659be58660241f9d17a16cac7b38"
      MYSQL_USER: branko
      MYSQL_PASSWORD: 22b319a4880b353aa9659be58660241f9
      MYSQL_DATABASE: database
    volumes:
      - ./mysql/exec/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 3316:3306
