
#include <stdio.h>
#include <stdlib.h>

int oops(){
   printf("oops this wasn't the char I was looking for\n");
   exit(1);
   return 0;
}
int main () {
   FILE *fp;
   char c;
   fp = fopen("flag.txt","r");
   
   if (fp==NULL)
   {
      printf("error opening file\n");
      exit(1);
   } 
fseek(fp,540,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,711,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,73,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,68,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,155,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,673,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,35,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,309,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,148,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,280,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,474,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,240,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,178,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,340,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,695,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,526,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,286,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,313,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,259,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,543,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,256,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,584,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,97,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,55,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,0,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,22,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,615,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,300,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,30,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,634,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,676,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,298,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,428,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,250,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,93,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,505,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,556,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,586,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,697,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,496,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,222,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,720,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,324,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,501,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,361,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,44,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,442,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,683,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,306,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,567,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,118,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,610,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,197,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,702,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,326,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,61,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,374,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,355,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,493,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,279,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,4,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,80,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,116,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,317,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,668,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,618,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,435,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,666,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,268,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,458,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,20,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,248,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,111,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,120,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,574,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,651,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,228,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,486,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,23,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,316,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,341,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,92,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,98,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,130,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,183,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,281,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,38,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,29,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,335,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,454,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,715,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,19,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,636,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,357,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,705,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,504,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,275,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,147,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,173,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,299,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,239,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,104,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,591,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,641,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,708,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,421,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,477,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,49,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,548,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,114,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,82,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,254,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,617,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,345,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,251,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,399,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,163,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,598,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,377,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,6,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,203,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,213,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,270,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,664,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,438,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,45,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,329,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,655,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,667,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,191,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,387,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,242,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,436,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,707,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,423,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,409,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,237,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,31,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,205,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,592,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,238,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,21,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,706,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,27,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,188,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,645,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,450,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,596,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,716,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,402,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,186,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,430,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,429,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,158,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,100,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,24,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,274,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,572,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,652,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,209,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,475,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,199,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,57,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,633,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,315,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,512,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,499,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,622,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,558,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,232,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,177,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,718,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,396,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,576,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,681,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,36,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,422,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,272,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,654,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,319,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,137,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,172,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,65,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,523,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,235,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,95,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,142,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,252,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,611,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,124,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,206,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,462,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,492,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,88,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,143,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,709,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,382,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,703,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,367,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,542,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,66,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,296,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,321,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,485,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,262,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,54,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,102,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,521,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,208,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,115,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,338,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,194,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,215,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,534,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,189,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,378,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,151,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,204,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,339,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,406,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,719,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,364,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,202,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,465,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,388,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,491,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,457,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,69,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,710,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,60,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,589,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,86,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,99,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,348,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,334,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,632,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,444,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,466,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,639,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,159,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,497,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,161,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,635,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,365,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,325,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,323,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,295,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,662,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,500,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,691,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,551,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,223,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,284,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,176,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,198,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,575,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,224,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,156,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,84,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,563,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,363,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,637,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,278,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,550,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,650,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,557,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,167,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,58,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,89,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,308,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,2,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,426,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,469,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,568,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,601,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,190,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,322,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,174,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,372,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,602,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,303,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,690,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,276,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,241,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,404,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,569,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,234,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,507,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,411,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,612,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,253,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,726,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,381,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,536,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,227,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,119,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,403,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,50,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,328,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,717,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,56,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,34,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,107,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,607,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,184,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,291,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,410,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,580,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,383,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,153,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,578,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,541,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,283,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,247,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,346,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,533,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,146,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,386,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,201,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,301,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,135,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,678,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,293,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,5,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,588,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,687,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,606,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,640,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,577,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,16,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,126,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,285,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,418,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,594,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,77,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,347,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,11,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,185,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,370,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,249,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,331,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,83,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,675,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,9,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,445,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,10,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,171,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,76,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,539,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,573,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,448,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,495,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,661,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,419,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,724,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,51,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,145,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,47,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,722,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,220,SEEK_SET);c=fgetc(fp);if(c != 44){oops();}
fseek(fp,289,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,79,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,397,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,128,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,671,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,53,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,110,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,616,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,434,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,665,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,166,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,131,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,516,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,379,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,369,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,168,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,271,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,629,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,40,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,621,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,32,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,427,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,677,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,517,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,600,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,547,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,105,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,653,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,265,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,553,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,663,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,565,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,244,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,255,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,304,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,524,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,609,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,590,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,169,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,527,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,389,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,546,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,424,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,136,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,425,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,549,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,307,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,226,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,13,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,693,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,349,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,1,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,525,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,342,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,522,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,292,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,71,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,694,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,559,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,613,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,337,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,685,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,552,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,480,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,391,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,519,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,417,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,356,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,561,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,318,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,311,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,207,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,33,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,684,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,187,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,464,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,447,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,670,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,498,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,333,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,443,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,302,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,170,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,453,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,352,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,605,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,508,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,28,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,25,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,619,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,15,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,26,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,264,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,359,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,144,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,479,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,219,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,471,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,74,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,134,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,413,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,165,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,721,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,400,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,96,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,258,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,392,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,327,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,90,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,656,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,530,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,393,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,109,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,488,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,581,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,63,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,414,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,700,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,597,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,446,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,149,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,312,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,62,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,288,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,456,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,603,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,243,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,463,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,192,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,17,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,132,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,461,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,625,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,193,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,412,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,42,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,196,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,182,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,478,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,394,SEEK_SET);c=fgetc(fp);if(c != 96){oops();}
fseek(fp,579,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,688,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,245,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,8,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,657,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,535,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,509,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,344,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,330,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,595,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,81,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,649,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,267,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,140,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,127,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,395,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,481,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,336,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,490,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,218,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,175,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,200,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,362,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,554,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,157,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,91,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,723,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,266,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,513,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,231,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,160,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,452,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,376,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,467,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,195,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,604,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,660,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,416,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,108,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,672,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,179,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,405,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,52,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,18,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,59,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,642,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,123,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,638,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,14,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,564,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,624,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,511,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,545,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,566,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,314,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,704,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,528,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,472,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,408,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,520,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,305,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,225,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,139,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,294,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,75,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,138,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,385,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,441,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,216,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,503,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,150,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,538,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,646,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,674,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,570,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,164,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,628,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,41,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,431,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,117,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,70,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,489,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,593,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,451,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,263,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,510,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,350,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,290,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,72,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,583,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,43,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,713,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,643,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,415,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,532,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,696,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,679,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,514,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,620,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,384,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,229,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,181,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,515,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,214,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,277,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,585,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,354,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,614,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,407,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,39,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,113,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,257,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,358,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,502,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,12,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,698,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,282,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,351,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,94,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,529,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,320,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,162,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,714,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,112,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,101,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,468,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,297,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,269,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,701,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,152,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,494,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,273,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,398,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,287,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,260,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,7,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,141,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,440,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,626,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,48,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,648,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,680,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,125,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,455,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,544,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,518,SEEK_SET);c=fgetc(fp);if(c != 47){oops();}
fseek(fp,154,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,64,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,482,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,437,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,473,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,506,SEEK_SET);c=fgetc(fp);if(c != 39){oops();}
fseek(fp,658,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,460,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,689,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,46,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,630,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,659,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,560,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,537,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,106,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,37,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,476,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,360,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,669,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,217,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,122,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,562,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,67,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,375,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,212,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,373,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,332,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,310,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,180,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,210,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,483,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,692,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,121,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,230,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,555,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,236,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,129,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,439,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,103,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,420,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,599,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,487,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,644,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,682,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,647,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,712,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,85,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,390,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,133,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,261,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,449,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,631,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,459,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,401,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,87,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,78,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,686,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,699,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,432,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,366,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,371,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,484,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,587,SEEK_SET);c=fgetc(fp);if(c != 92){oops();}
fseek(fp,221,SEEK_SET);c=fgetc(fp);if(c != 45){oops();}
fseek(fp,582,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,343,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,368,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,623,SEEK_SET);c=fgetc(fp);if(c != 10){oops();}
fseek(fp,725,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,3,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,470,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,627,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,211,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}
fseek(fp,353,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,246,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,380,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,531,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,608,SEEK_SET);c=fgetc(fp);if(c != 95){oops();}
fseek(fp,571,SEEK_SET);c=fgetc(fp);if(c != 32){oops();}
fseek(fp,233,SEEK_SET);c=fgetc(fp);if(c != 124){oops();}
fseek(fp,433,SEEK_SET);c=fgetc(fp);if(c != 46){oops();}


   printf("CORRECT!\n");
   fclose(fp);
   
   return(0);
}


